# Generated by Django 5.2 on 2025-06-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('viewer', 'Visualizador'), ('editor', 'Editor'), ('admin', 'Administrador')], default='viewer', max_length=20),
        ),
    ]
